<?php
/**
 * @file
 * Deals with installation, uninstallation and updates
 *
 */

/**
 * Recreate missing translation nodes.
 */
function services_advisor_base_update_7013() {
  $query = db_select('node', 'n')
    ->fields('n', array('tnid'))
    ->condition('n.type', 'service_location')
    ->groupBy('tnid')
    ->having('COUNT(nid) < :langnum', array(':langnum' => count(locale_language_list())));
  $results = $query->execute()->fetchCol();

  foreach (node_load_multiple($results) as $node) {
    foreach(services_advisor_base_get_missing_translations($node) as $missing_lang) {
      services_advisor_base_create_translation_clone($node, $missing_lang);
    }
  }
}
